version: '3'
services:
  epochtalk-api-tests:
    build: .
    ports:
      - "1025:1025"
    depends_on:
      - epochtalk
    links:
      - epochtalk
    environment:
      HOST: http://epochtalk:8080
